version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m unittest discover tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build